### ISSUE TITLE
Remove public display of email address

### ISSUE THREAD

**Issue by anubis71x** [ytrushkov/wotcup#5]
- [x] Remove public display of email address and other contact info (aim, jabber, etc) on profile page.

- [x] Remove useless contact forms (aim, jabber, etc) from join.php and edit.php.

**Comment by anubis71x** [comment]
first item completed, unable to push

**Comment by ytrushkov** [comment]
@anubis71x , need more details on the first item - we don't want to display it to anybody? or just hide from one who haven't logged in?

**Comment by ytrushkov** [comment]
Can we still show it if:
1) the active user is logged in
2) Clan has ['MsgMe'] == "Yes"

**Comment by anubis71x** [comment]
We can if you want, sure. The main thing is I don't want to expose people's email in public. And AIM, MSN, etc are obsolete in my opinion.
