### ISSUE TITLE
Incorrect graph is shown for the clan progress

### ISSUE THREAD

**Issue by ytrushkov** [ytrushkov/wotcup#8]
![screen shot 2017-04-03 at 5 54 13 pm](https://cloud.githubusercontent.com/assets/5460077/24637513/a508002e-1896-11e7-964c-75b3ae9f7a7f.png)

**Comment by anubis71x** [comment]
I deleted the bad image and it generated a correct image, but the new image isn't getting posted. It may correct itself after a game is played.

**Comment by anubis71x** [comment]
Looks to be working at the moment.
